# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

##@ Key Management
.PHONY: cache-keys
cache-keys: ## Download Red Hat signing keys from official sources to ~/.coco-pattern/
	@mkdir -p ~/.coco-pattern
	@echo "Fetching Red Hat sigstore public key (release key 3)..."
	@curl -fsSL https://www.redhat.com/security/data/63405576.txt -o ~/.coco-pattern/SIGSTORE-redhat-release3
	@echo "  Cached at ~/.coco-pattern/SIGSTORE-redhat-release3"
	@echo "Fetching Red Hat GPG public key (release key 2)..."
	@curl -fsSL https://access.redhat.com/security/data/fd431d51.txt -o ~/.coco-pattern/RPM-GPG-KEY-redhat-release
	@echo "  Cached at ~/.coco-pattern/RPM-GPG-KEY-redhat-release"
	@echo "Done. Verify fingerprints at https://access.redhat.com/security/team/key/"


##@ Reference Value Collection
.PHONY: collect-firmware-refvals
collect-firmware-refvals: ## Collect firmware reference values (bare metal, default)
	@scripts/collect-firmware-refvals.sh

.PHONY: collect-azure-refvals
collect-azure-refvals: ## Collect PCR reference values (Azure)
	@scripts/collect-firmware-refvals.sh --platform azure

##@ DCAP Trustee Collateral (for RVPS quote verification -- separate from PCK provisioning)
.PHONY: collect-dcap-collateral
collect-dcap-collateral: ## Collect DCAP collateral for Trustee RVPS (TCB info, QE identity, PCK CRL). Requires --fmspc FMSPC.
	@scripts/collect-dcap-collateral.sh $(ARGS)

##@ DCAP Offline Provisioning (disconnected cluster PCK cert workflow)
## Uses Azure cluster (Online mode) as intermediary to obtain PCK certs
## for the disconnected baremetal cluster (Offline mode).
##
## Full workflow: make dcap-offline-provision
## Individual steps: make dcap-extract-platform-data / dcap-apply-platform-data / etc.
##
## Environment:
##   KUBECONFIG_DISCONNECTED  node-02 kubeconfig (default: ~/node-02-output/421_build/auth/kubeconfig)
##   KUBECONFIG_CONNECTED     Azure kubeconfig (default: ~/azure/kubeconfig)

DCAP_NS := intel-dcap-operator-system
DCAP_WORK_DIR := $(HOME)/.coco-pattern/dcap-offline

.PHONY: dcap-offline-provision
dcap-offline-provision: ## Run full DCAP offline PCK provisioning workflow (extract -> Azure register -> apply back)
	@scripts/dcap-offline-provision.sh all

.PHONY: dcap-extract-platform-data
dcap-extract-platform-data: ## Step 1: Extract platform-data secrets from disconnected cluster
	@scripts/dcap-offline-provision.sh extract-platform-data

.PHONY: dcap-apply-platform-data
dcap-apply-platform-data: ## Step 2: Apply platform-data secrets to Azure (connected) cluster
	@scripts/dcap-offline-provision.sh apply-platform-data

.PHONY: dcap-wait-for-pck
dcap-wait-for-pck: ## Step 3: Wait for Azure DCAP operator to create PCK secrets
	@scripts/dcap-offline-provision.sh wait-for-pck

.PHONY: dcap-extract-pck
dcap-extract-pck: ## Step 4: Extract PCK secrets from Azure cluster
	@scripts/dcap-offline-provision.sh extract-pck

.PHONY: dcap-apply-pck
dcap-apply-pck: ## Step 5: Apply PCK secrets to disconnected cluster
	@scripts/dcap-offline-provision.sh apply-pck

.PHONY: dcap-verify
dcap-verify: ## Verify QGS pods and DCAP secrets on disconnected cluster
	@scripts/dcap-offline-provision.sh verify

##@ Hardware Detection
.PHONY: detect-hardware
detect-hardware: ## Detect hardware profile from cluster nodes (requires KUBECONFIG or oc login)
	@echo "Detecting hardware profile from cluster nodes..."
	@echo "---"
	@CPU_VENDOR=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-model\.vendor_id}' 2>/dev/null) && \
	TDX_ENABLED=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-security\.tdx\.enabled}' 2>/dev/null) && \
	SNP_ENABLED=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-security\.sev\.snp}' 2>/dev/null) && \
	GPU_PRESENT=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.nvidia\.com/gpu\.present}' 2>/dev/null) && \
	echo "CPU Vendor:  $${CPU_VENDOR:-unknown}" && \
	echo "TDX Enabled: $${TDX_ENABLED:-false}" && \
	echo "SNP Enabled: $${SNP_ENABLED:-false}" && \
	echo "GPU Present: $${GPU_PRESENT:-false}" && \
	echo "---" && \
	if [ "$${CPU_VENDOR}" = "Intel" ] && [ "$${TDX_ENABLED}" = "true" ]; then \
		if [ "$${GPU_PRESENT}" = "true" ]; then \
			echo "Recommended profile: intel-tdx-gpu"; \
		else \
			echo "Recommended profile: intel-tdx"; \
		fi; \
	elif [ "$${CPU_VENDOR}" = "AuthenticAMD" ] || [ "$${SNP_ENABLED}" = "true" ]; then \
		if [ "$${GPU_PRESENT}" = "true" ]; then \
			echo "Recommended profile: amd-snp-gpu"; \
		else \
			echo "Recommended profile: amd-snp"; \
		fi; \
	else \
		echo "Could not determine hardware profile."; \
		echo "Ensure NFD operator is running and node labels are populated."; \
		echo "Set global.hardware.profile manually in values-global.yaml"; \
	fi && \
	echo "" && \
	echo "To apply: edit values-global.yaml and set global.hardware.profile to the recommended value."
