# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

##@ Key Management
.PHONY: cache-keys
cache-keys: ## Download Red Hat signing keys from official sources to ~/.coco-pattern/
	@mkdir -p ~/.coco-pattern
	@echo "Fetching Red Hat sigstore public key (release key 3)..."
	@curl -fsSL https://www.redhat.com/security/data/63405576.txt -o ~/.coco-pattern/SIGSTORE-redhat-release3
	@echo "  Cached at ~/.coco-pattern/SIGSTORE-redhat-release3"
	@echo "Fetching Red Hat GPG public key (release key 2)..."
	@curl -fsSL https://access.redhat.com/security/data/fd431d51.txt -o ~/.coco-pattern/RPM-GPG-KEY-redhat-release
	@echo "  Cached at ~/.coco-pattern/RPM-GPG-KEY-redhat-release"
	@echo "Done. Verify fingerprints at https://access.redhat.com/security/team/key/"


##@ Reference Value Collection
.PHONY: collect-firmware-refvals
collect-firmware-refvals: ## Collect firmware reference values (bare metal, default)
	@scripts/collect-firmware-refvals.sh

.PHONY: collect-azure-refvals
collect-azure-refvals: ## Collect PCR reference values (Azure)
	@scripts/collect-firmware-refvals.sh --platform azure

##@ DCAP Trustee Collateral (for RVPS quote verification -- separate from PCK provisioning)
.PHONY: collect-dcap-collateral
collect-dcap-collateral: ## Collect DCAP collateral for Trustee RVPS (TCB info, QE identity, PCK CRL). Requires --fmspc FMSPC.
	@scripts/collect-dcap-collateral.sh $(ARGS)

##@ DCAP Offline PCK Provisioning
## Runs pck-cert-tool via podman on the jump host to provision PCK
## certificates for a disconnected TDX cluster. The jump host bridges
## the cluster (internal) and Intel PCS API (internet).
##
## Full workflow: make dcap-offline-provision INTEL_PCS_API_KEY=your-key
## Certs cached: ~/.coco-pattern/dcap-offline/
##
## Prerequisites: podman, oc, DCAP operator deployed (Offline mode)
## Get API key:   https://api.portal.trustedservices.intel.com/

.PHONY: dcap-offline-provision
dcap-offline-provision: ## Full offline PCK provisioning: register + cache + verify
	@scripts/dcap-offline-provision.sh all

.PHONY: dcap-register-pck
dcap-register-pck: ## Register platforms with Intel PCS via podman (needs INTEL_PCS_API_KEY)
	@scripts/dcap-offline-provision.sh register-pck

.PHONY: dcap-cache-pck
dcap-cache-pck: ## Cache PCK secrets locally to ~/.coco-pattern/dcap-offline/
	@scripts/dcap-offline-provision.sh cache-pck

.PHONY: dcap-restore-pck
dcap-restore-pck: ## Re-apply cached PCK secrets to cluster
	@scripts/dcap-offline-provision.sh restore-pck

.PHONY: dcap-status
dcap-status: ## Show DCAP platform-data and PCK secret status
	@scripts/dcap-offline-provision.sh status

.PHONY: dcap-verify
dcap-verify: ## Full DCAP verification (CR, pods, secrets, cert cache)
	@scripts/dcap-offline-provision.sh verify

##@ Hardware Detection
.PHONY: detect-hardware
detect-hardware: ## Detect hardware profile from cluster nodes (requires KUBECONFIG or oc login)
	@echo "Detecting hardware profile from cluster nodes..."
	@echo "---"
	@CPU_VENDOR=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-model\.vendor_id}' 2>/dev/null) && \
	TDX_ENABLED=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-security\.tdx\.enabled}' 2>/dev/null) && \
	SNP_ENABLED=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.feature\.node\.kubernetes\.io/cpu-security\.sev\.snp}' 2>/dev/null) && \
	GPU_PRESENT=$$(oc get nodes -o jsonpath='{.items[0].metadata.labels.nvidia\.com/gpu\.present}' 2>/dev/null) && \
	echo "CPU Vendor:  $${CPU_VENDOR:-unknown}" && \
	echo "TDX Enabled: $${TDX_ENABLED:-false}" && \
	echo "SNP Enabled: $${SNP_ENABLED:-false}" && \
	echo "GPU Present: $${GPU_PRESENT:-false}" && \
	echo "---" && \
	if [ "$${CPU_VENDOR}" = "Intel" ] && [ "$${TDX_ENABLED}" = "true" ]; then \
		if [ "$${GPU_PRESENT}" = "true" ]; then \
			echo "Recommended profile: intel-tdx-gpu"; \
		else \
			echo "Recommended profile: intel-tdx"; \
		fi; \
	elif [ "$${CPU_VENDOR}" = "AuthenticAMD" ] || [ "$${SNP_ENABLED}" = "true" ]; then \
		if [ "$${GPU_PRESENT}" = "true" ]; then \
			echo "Recommended profile: amd-snp-gpu"; \
		else \
			echo "Recommended profile: amd-snp"; \
		fi; \
	else \
		echo "Could not determine hardware profile."; \
		echo "Ensure NFD operator is running and node labels are populated."; \
		echo "Set global.hardware.profile manually in values-global.yaml"; \
	fi && \
	echo "" && \
	echo "To apply: edit values-global.yaml and set global.hardware.profile to the recommended value."
