global:
  pattern: coco-demo-pattern
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # This defines whether or not to use upstream resources for CoCo.
  cocoUpstream: true
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
