global:
  cocoUpstream: true
  cocoConverged: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore


sandbox:
  sshKey: secret/data/global/ssh-key
  upstreamCatalogVersion: 1.7.0-22
  azure: true
  peerpodsCreds: secret/data/global/azure
  azureConfig: secret/data/global/azure-cluster-metadata
  # These variables today limit to one cluster
  # revise using imperative framework to infer from cluster vars
  azureResGroup: 'openenv-9vh7l'
  azureRegion: 'eastus'
  azureSubnet: '/subscriptions/ce3de9a8-39e2-4cb8-a5cc-369e7043f5f4/resourceGroups/sandboxer-8lw7x-rg/providers/Microsoft.Network/virtualNetworks/sandboxer-8lw7x-vnet/subnets/sandboxer-8lw7x-worker-subnet'
  azureNSG: '/subscriptions/ce3de9a8-39e2-4cb8-a5cc-369e7043f5f4/resourceGroups/sandboxer-8lw7x-rg/providers/Microsoft.Network/networkSecurityGroups/sandboxer-8lw7x-nsg'
