global:
  cocoUpstream: true
  cocoConverged: true

secretStore:
  name: vault-backend
  kind: ClusterSecretStore


sandbox:
  upstreamCatalogVersion: 1.7.0-22
  azure: true
  peerpodsCreds: secret/data/global/azure
  azureConfig: secret/data/global/azure-cluster-metadata
