{{ if .Values.sandbox.azure }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm-template
  namespace: openshift-sandboxed-containers-operator
data:
  CLOUD_PROVIDER: "azure"
  VXLAN_PORT: "9000"
  AZURE_INSTANCE_SIZE: "Standard_DC2as_v5"
  AZURE_RESOURCE_GROUP: "{{`{{ .resGroup }}`}}"
  AZURE_REGION: "{{`{{ .region }}`}}"
  AZURE_SUBNET_ID: "{{`{{ .subnet }}`}}" 
  AZURE_NSG_ID: "{{`{{ .nsg }}`}}"
  DISABLECVM: "false" 
  AZURE_IMAGE_ID: "****"
  DISABLE_CLOUD_CONFIG: "true"
  PROXY_TIMEOUT: "5m"
{{ end }}