{{- if .Values.sandbox.azure }}
{{- if not .Values.sandbox.imageBuild }}
---
# CJB Don't
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: peer-pods-cm
#   namespace: openshift-sandboxed-containers-operator
# data:
#   CLOUD_PROVIDER: "azure"
#   VXLAN_PORT: "9000"
#   # AZURE_INSTANCE_SIZE: "Standard_DC2as_v5" # standard peer-pod
#   AZURE_INSTANCE_SIZE: "Standard_B2als_v2" # CoCo peer pod
#   AZURE_RESOURCE_GROUP: "{{ .Values.sandbox.azureResGroup }}"
#   AZURE_REGION: "{{ .Values.sandbox.azureRegion }}"
#   AZURE_SUBNET_ID: "{{ .Values.sandbox.azureSubnet }}" 
#   AZURE_NSG_ID: "{{ .Values.sandbox.azureNSG }}"
#   DISABLECVM: "true" # CoCo requirement
#   AZURE_IMAGE_ID: ""
#   #DISABLE_CLOUD_CONFIG: "true"
#   #AA_KBC_PARAMS: "cc_kbc::https://kbs-service-kbs-operator-system.{{ .Values.global.hubClusterDomain }}"
#   AA_KBC_PARAMS: "cc_kbc::http://kbs-service.trustee-operator-system.svc.cluster.local:8080"
#   PROXY_TIMEOUT: "5m"
{{- end }}
{{- end }}