{{ if .Values.sandbox.azure }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: peer-pods-cluster-metadata-eso
  namespace: openshift-sandboxed-containers-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  target:
    name: peer-pods-cluster-metadata
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.sandbox.azureConfig }}
{{ end }}