global:
  pattern: coco-pattern

dcapOperator:
  enabled: true
  mode: "Offline"
  modeConfig: "{}"
  nodeSelector:
    - "intel.feature.node.kubernetes.io/sgx=true"
  pckSecrets: []

secretStore:
  name: ""
  kind: ""
