apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: openshift-operators
data:
  policy.rego: |
    package policy

    default allow = false
    allow {
            input["tee"] != "sample"
    }
