{{ if .Values.global.cocoUpstream }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kbs-operator-system
  namespace: kbs-operator-system
spec:
  channel: alpha
  name: trustee-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
{{ end }}