apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-slim
  labels:
    app: coco-demo-slim
spec:
  runtimeClassName: kata-cc-tdx

  initContainers:
  - name: fetch-key
    image: quay.io/rh-ee-chbutler/microsleep:latest
    command:
    - sh
    - -c
    - curl -L https://gist.githubusercontent.com/butler54/21a0e98d56796c2bff35f9e823f52a7f/raw/923cde0849a1755af70fee031e0f021659e346d2/raw.txt -o /keys/magickey.txt
    volumeMounts:
    - name: keys
      mountPath: /keys
  containers:
  - name: coco-demo-slim
    image: quay.io/rh-ee-chbutler/microsleep:latest
    command:
    - sleep
    - "36000"
    securityContext:
      privileged: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: keys
      mountPath: /keys
  volumes:
  - name: keys
    emptyDir:
      medium: Memory

