{{- if and .Values.dcapOperator.enabled (eq .Values.dcapOperator.mode "Offline") }}
{{- range .Values.dcapOperator.pckSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    fmspc: {{ .fmspc | quote }}
    app.kubernetes.io/part-of: intel-tdx-dcap
  annotations:
    argocd.argoproj.io/sync-wave: "25"
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
